import React from 'react'

const Dashbord = () => {
  return (
    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis dolorum vel sapiente magnam laboriosam ipsum repudiandae mollitia nisi, fuga quaerat debitis, impedit odit assumenda id officia repellendus nobis quae autem nulla voluptatibus temporibus voluptas saepe. Placeat nam aspernatur mollitia facilis ipsum vitae consectetur maiores distinctio? Suscipit aliquam minus voluptatem doloribus numquam deserunt et temporibus, tempore sapiente placeat dolores iste aperiam mollitia corporis veniam totam facilis magnam odio amet voluptatum perspiciatis. Ratione qui est repellat dicta nulla fugit dolorum facere nobis! Asperiores, possimus facere repudiandae maxime enim, ipsum blanditiis explicabo inventore, sunt placeat soluta hic eligendi magni. Repellendus similique odio distinctio rerum quasi dolor saepe. Enim tenetur quis repudiandae fugit, ut aperiam sunt libero voluptatum vitae? Quos, at modi? Cumque natus neque, non minima iusto voluptates earum maxime distinctio aperiam nulla ipsum quam et doloremque. Consequatur architecto, sed provident nihil fugiat nobis ratione aspernatur pariatur reiciendis, officia sint commodi? Voluptatibus, quae doloribus sint explicabo tenetur harum modi possimus rerum dolore ex iure facilis ullam voluptates enim cupiditate voluptatum. Nostrum iste quia soluta laudantium repellendus, corrupti perferendis? Placeat, reiciendis nam! Accusamus delectus magni corrupti. Deleniti magnam corrupti ut tenetur expedita libero qui, fugiat delectus non harum aspernatur pariatur, repudiandae cupiditate consequatur vitae atque quae possimus voluptatibus enim veniam sapiente nihil quidem inventore. Quia tenetur dolorum distinctio quidem sunt? Culpa consectetur dicta minus odit? Unde, rem maxime dolorum placeat tenetur sint facere possimus ratione asperiores accusantium quam a voluptatum ut consectetur eius ex exercitationem at quis amet repellat vitae. Facere obcaecati deleniti vitae.</div>
  )
}

export default Dashbord
